version: '3.8'
services:
  backend: 
    image: alpine:latest  
    working_dir: /app 
    command: >
     sh -c "cp sql_app/backend_setup.sh ./ 
     && chmod 766 backend_setup.sh 
     && ./backend_setup.sh 
     && tail -f /dev/null"
    ports:
      - "8000:8000"  # Map Uvicorn's default port
    volumes:
      - '../sql_app:/app/sql_app:cached'
